[theme]
primaryColor="#4a8af4"
backgroundColor="#121212"
secondaryBackgroundColor="#1E1E1E"
textColor="#E0E0E0"
font="sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
